EthWorks/ethereum.rb

lib/ethereum/contract.rb
spec/ethereum/contract_blockchain_spec.rb
spec/ethereum/contract_event_spec.rb
spec/ethereum/contract_spec.rb

Introduce new syntax for contract methods call.
Before:
contract.call_name(args)
contract.nf_changed(args) 
After:
contract.call.name(args)
contract.new_filter.changed(args)
Finalise refactoring of contract class and dynamic proxies.

Introduce new syntax for contract methods call

---

.travis.yml
bin/install_parity
lib/ethereum/client.rb
spec/ethereum/signed_transaction_blockchain_spec.rb

Ropsten blockchain became to big to download each time by travis.
So this commit switches parity chain from ropsten to dev.

Switch CI from test chain to dev chain

---

lib/ethereum/ipc_client.rb

Relevant issue: #12 
The fix adds a clear error message instead of "Errno::EINVAL: Invalid argument - connect(2)"
I think it could be useful if any other default path pops up

Add "Ipc file not found" error

---

lib/ethereum/encoder.rb
lib/ethereum/formatter.rb

this is a fix to add support for actual byte strings containing string-values from \x00 to \x0F.
This fix makes it easier to add actual byte data to a contract and retrieve it:
```
["67b176705b46206614219f47a05aee7ae6a3edbe850bbbe214c536b989aea4d2"].pack('H*')#
contract.call.get_hash.unpack1('H*')
```
will actually return the provided string

add support for real byte strings

---

PREREQUISITES.md

The code was saying:
Or install it yourself as:
$ gem install ethereum.eb 
It should be ethereum.rb

Updated the instructions

---

lib/ethereum/transaction.rb

There is a problem when the transaction has already been mined in wait_for_miner that returns nil.
Also sleep sooner makes to wait for no reason. We can check and then wait if hasn't been mined.

Transaction wait_for_miner fails if the transaction has been already mined

---

lib/ethereum/deployment.rb

In Deployment the method mined? doesn't work, internally raises an exception because lacks the `eth_` part. (A typo that couldn't be seen?)
I also made the same as #28 to return first the result, and then wait if it's needed. Because now we are waiting for no reason.

Fix mined? in deployment class

---

README.md
lib/ethereum/contract.rb
spec/ethereum/contract_spec.rb
spec/truffle/README.md
spec/truffle/build/contracts/Migrations.json
spec/truffle/build/contracts/TestContractOne.json
spec/truffle/contracts/Migrations.sol
spec/truffle/contracts/TestContractOne.sol
spec/truffle/migrations/1_initial_migration.js
spec/truffle/migrations/2_deploy_contracts.js
spec/truffle/test/TestContractOne.js
spec/truffle/truffle.js

Edits to Ethereum::Contract.create to optionally use Truffle artifacts to initialize a contract object.

Simple integration with Truffle

---

lib/ethereum/http_client.rb

Currently,  `Ethereum::HttpClient.new('http://example.com/testnet')` would initialize an http client with wrong URI (http://example.com), stripping out the path. This PR fixes that.

Fix Ethereum::HttpClient

---

.gitignore
lib/ethereum/http_client.rb

This PR allows callers to supply a proxy URL to the underlying Net:Http library. This can be provide in the form `http://<user>:<password>@<host>:<port>`.
This is useful for applications that are hosted on services like Heroku that have highly dynamic IP address and use tools like Proximo or Fixie.

updated to allow passing in of proxy data

---

README.md

This PR adds some basic instructions on how to listen for Solidity contract events.
This is taken from KR8OS' working products so it works reliably.

Add instructions for listening to contract events

---

lib/ethereum/client.rb
lib/ethereum/contract.rb
spec/ethereum/client_spec.rb

Fixes issues with colliding transactions, additionally allow passing alternate transaction nonce value if needed. Please comment if you see a better solution for sending more than one similar transaction per single mined block.
Relates to: https://github.com/EthWorks/ethereum.rb/issues/35

Use pending transaction nonce as a default

---

ethereum.gemspec

We're using rails 4.x, and can't easily migrate to 5.x to have ActiveSupport 5.x.
Fixes #32

Relax activesupport dependency

---

lib/ethereum/contract.rb

This PR solves a problem for different versions of Truffle. Different versions use different JSON keys to store the contract's bytecode. Here, we look for both keys before failing.

Adds support for different truffle version builds

---

lib/ethereum/solidity.rb

--add-std option is removed at solidity 0.4.21.
The compilation is failed with following error.
```
pry(main)> contract =  Ethereum::Contract.create(file: '/tmp/test.sol', client: ipc)
Ethereum::CompilationError: unrecognised option '--add-std'
from /home/iberianpig/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ethereum.rb-2.1.8/lib/ethereum/solidity.rb:36:in `execute_solc'
```
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.21+commit.dfe3193c.Linux.g++
```
* https://github.com/ethereum/solidity/issues/3695
* https://github.com/ethereum/solidity/commit/5ab4a1ae7819004415293bf72a86824beb43cd51

remove "--add-std" arg, deprecated in solidity 0.4.21

---

PREREQUISITES.md

This library has been tested with 0.4.16.
ref: https://github.com/EthWorks/ethereum.rb/pull/125

Tested with solc 0.4.16

---

.travis.yml

Removed Ruby 2.3 because it is not supported.
```
Ruby 2.3
status: eol
release date: 2015-12-25
EOL date: 2019-03-31
```
* https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/
* https://www.ruby-lang.org/en/downloads/branches/

Support of Ruby 2.3 has ended.

---

.travis.yml

Ruby 2.7.0 Released.
https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

Ruby 2.7.0 Released

---

PREREQUISITES.md
bin/install_parity
spec/ethereum/solidity_spec.rb
spec/fixtures/ContractWithError.sol
spec/fixtures/TestContract.sol
spec/fixtures/greeter.sol

I'm upgrade solc version to [0.5.16](https://github.com/ethereum/solidity/releases/tag/v0.5.16).
In solc 0.5.12 has been changed sort order of JSON ABI.
> ABI Output: Change sorting order of functions from selector to kind, name.
see: https://github.com/ethereum/solidity/releases/tag/v0.5.12

Tested with solc 0.5.16

---

lib/ethereum/formatter.rb
spec/ethereum/formatter_spec.rb

fix: https://github.com/EthWorks/ethereum.rb/issues/139

BigDecimal.new is deprecated in Ruby 2.7

---

lib/ethereum/contract.rb

Fixes ability of changing nonce which is introduced by https://github.com/EthWorks/ethereum.rb/pull/58, and later it seems to be removed by https://github.com/EthWorks/ethereum.rb/pull/112

Fix allowance of passing alternate transaction nonce value on contract

---

ethereum.gemspec
lib/ethereum.rb
lib/ethereum/contract_event.rb
lib/ethereum/function.rb

- replaces `eth-patched` with `eth` (reverts #165) - I'm co-maintainer now
- replaces `digest-sha3` (unmaintained) with `keccak` - I'm maintaining that one too
- adds `ffi` (couldn't get `rspec` to work without)
- bumped `rake` to 13.0
- bumped some minor versions

gems: bump dependencies
